### ISSUE TITLE
Create ClassPathAnnotationBased scanner.

### ISSUE THREAD

**Issue by OlehYakovenko** [bobocode-breskul/bring#14]
- should scan the provided package to search all desired classes by the specified filter
- scanner should be implemented using the reflection library encapsulated in our ReflectionUtils class
- **search package name** is method attribute, **results filter** is method attribute

**Comment by JoshukLite** [comment]
Class main goal to provide BeanDefinitions found by provided class path. It should recursively scan it and it's children.
It should have a method that takes `String` object or array of `String` objects as path value and return `Collection` of found BeanDefinitions. Something like:
- `public List<BeanDefinition> scan(String... rootPacakges)`

This scanner class should be configurable in any way (setters or constructor) so it could be adjusted to desired logic. Possible configuration properties:
- bean name generator (this might be mandatory)
- bean definition factory
- include filters
- exclude filters

Base implementation could return a list of found class names or a list of found classes.

Advance implementation should return a collection of BeanDefinitions. BeanDefinitions might be created by provided factory.
