### ISSUE TITLE
Spike Definition object for class

### ISSUE THREAD

**Issue by IIUPAMET** [bobocode-breskul/bring#2]
We need to create a class that allows us to define parameters describing metadata for our class.

- Create a simple class.
- Develop a base definition class.
- Prepare a demo where we build our definition class using a reflection API.

**Comment by golichenko02** [comment]
- create packages: config, parsing, support

parsing:


 - Create AliasRegistry interface  (package registry)
 - Create BeanDefinitionRegistry interface that extends AliasRegistry and corresponding implementation that will store the BeanDefinition by bean name in the map (package registry)
 - Create AnnotatedBeanDefinitionReader

**Comment by hladchenko** [comment]
Branch: feature/bean-definition

**Comment by golichenko02** [comment]
Updated task description:

* create packages: config, registry, support
registry:
* Create AliasRegistry interface (package registry) public API: -  void registerAlias(String name, String alias); -  void removeAlias(String alias); -  boolean isAlias(String name);| - String[] getAliases(String name); 
* Create BeanDefinitionRegistry interface that extends AliasRegistry and corresponding implementation (SimpleBeanDefinitionRegistry) that stores the BeanDefinition by bean name in the bean definition map and and alias by bean name in the alias map (package registry)  BeanDefinitionRegistry interface public API: - void registerBeanDefinition(String beanName, BeanDefinition beanDefinition) -  void removeBeanDefinition(String beanName) throws NoSuchBeanDefinitionException; - BeanDefinition getBeanDefinition(String beanName) throws NoSuchBeanDefinitionException; - boolean containsBeanDefinition(String beanName); - String[] getBeanDefinitionNames(); - Return the names of all beans defined in this registry. - int getBeanDefinitionCount(); - boolean isBeanNameInUse(String beanName); - Determine whether the given bean name is already in use within this registry, 
* Create AnnotatedBeanDefinitionReader with method registerBean that creates instance of BeanDefinition and store it to BeanDefinitionRegistry :  registerBean(private <T> void doRegisterBean(Class<T> beanClass, @Nullable String name, Class<? extends Annotation>[] qualifiers, @Nullable Supplier<T> supplier) . Optionally, we can overload it with variety of input params.   config:
* Create BeanDefinition interface with public api - void setDependsOn(String... dependsOn); -String[] getDependsOn(); - void setInstanceSupplier(Supplier<?> instanceSupplier); - Supplier<?> getInstanceSupplier(); - void setScope(String scope); - String getScope(); - boolean isSingleton(); - boolean isPrototype(); - void setAutowireCandidate(boolean autowireCandidate); - boolean isAutowireCandidate(); - void setPrimary(boolean primary); - boolean isPrimary();  
* Create abstract class GenericBeanDefinition that implements  BeanDefinition interface, handles common logic and inheritor class AnnotatedGenericBeanDefinition for bean definitions created via annotation config. - GenericBeanDefinition should have following properties:  String[] dependsOn  - stores the autowire candidates (names of the beans)  that this bean depends on being initialized boolean autowireCandidate - marks if the bean is a candidate for getting autowired into some other bean  boolean primary  - marks whether this bean is a primary autowire candidate. String scope -  the name of the target scope for the bean (SINGLETON, PROTOTYPE) private Supplier<?> instanceSupplier - the callback function for creating an instance of the bean;   support:
* Create BeanDefinitionReaderUtils with utility methods that  handle the bean definition reader implementations - GenericBeanDefinition createBeanDefinition(…); - String generateBeanName(…); - void registerBeanDefinition(…); - think about other useful methods that may handle common logic

**Comment by golichenko02** [comment]
**Updated Task Description:**

Create three distinct packages: `config`, `registry`, and `support`.

**Registry Package:**

In the `registry` package, the objective is to design an `AliasRegistry` interface with a public API for managing aliases.

- [ ] Implement the `AliasRegistry` interface with the following methods:

   - `void registerAlias(String name, String alias);`
   - `void removeAlias(String alias);`
   - `boolean isAlias(String name);`
   - `String[] getAliases(String name);`

- [ ] Create a `BeanDefinitionRegistry` interface that extends the `AliasRegistry` interface. Additionally, develop a corresponding implementation named `SimpleBeanDefinitionRegistry` that stores `BeanDefinition` objects by bean name in the bean definition map and aliases by bean name in the alias map.

`BeanDefinitionRegistry` interface public API:

- [ ] `void registerBeanDefinition(String beanName, BeanDefinition beanDefinition);`
- [ ] `void removeBeanDefinition(String beanName) throws NoSuchBeanDefinitionException;`
- [ ] `BeanDefinition getBeanDefinition(String beanName) throws NoSuchBeanDefinitionException;`
- [ ] `boolean containsBeanDefinition(String beanName);`
- [ ] `String[] getBeanDefinitionNames();` - Returns the names of all beans defined in this registry.
- [ ] `int getBeanDefinitionCount();`
- [ ] `boolean isBeanNameInUse(String beanName);` - Checks if the given bean name is already in use within this registry.

- [ ] Create an `AnnotatedBeanDefinitionReader` with a method `registerBean` that generates instances of `BeanDefinition` and stores them in the `BeanDefinitionRegistry`. Optionally, provide overloaded methods to support various input parameters.

**Config Package:**

In the `config` package, you need to create a `BeanDefinition` interface with the following public API:

- [ ] `void setDependsOn(String... dependsOn);`
- [ ] `String[] getDependsOn();`
- [ ] `void setInstanceSupplier(Supplier<?> instanceSupplier);`
- [ ] `Supplier<?> getInstanceSupplier();`
- [ ] `void setScope(String scope);`
- [ ] `String getScope();`
- [ ] `boolean isSingleton();`
- [ ] `boolean isPrototype();`
- [ ] `void setAutowireCandidate(boolean autowireCandidate);`
- [ ] `boolean isAutowireCandidate();`
- [ ] `void setPrimary(boolean primary);`
- [ ] `boolean isPrimary();`
- [ ] `void setBeanClassName(String beanClassName);`
- [ ] `String getBeanClassName();`

Additionally, create an abstract class named `GenericBeanDefinition` that implements the `BeanDefinition` interface. This class should handle common logic. Create an inheritor class named `AnnotatedGenericBeanDefinition` specifically for bean definitions created via annotation config. `GenericBeanDefinition` should have the following properties:

- `String[] dependsOn`: Stores the autowire candidates (names of the beans) that this bean depends on being initialized.
- `boolean autowireCandidate`: Marks whether the bean is a candidate for autowiring into other beans.
- `boolean primary`: Marks whether this bean is a primary autowire candidate.
- `String scope`: The name of the target scope for the bean (SINGLETON, PROTOTYPE).
- `private Supplier<?> instanceSupplier`: The callback function for creating an instance of the bean.
- `String beanClass`: the bean class name of this bean definition.
**Support Package:**

In the `support` package, create `BeanDefinitionReaderUtils` with utility methods for handling bean definition reader implementations, including:

- [ ] `GenericBeanDefinition createBeanDefinition(…);`
- [ ] `String generateBeanName(…);`
- [ ] `void registerBeanDefinition(…);`

Consider other useful methods that may handle common logic as needed.
