### ISSUE TITLE
Spike Package scanner

### ISSUE THREAD

**Issue by IIUPAMET** [bobocode-breskul/bring#3]
Our project requires scanning to find classes that need to be registered.

- We need to define the starting point from where the scanning process begins.
- Next, we create a place to store all the classes that are found.
- Please consider an API for retrieving these classes.

**Comment by JoshukLite** [comment]
0. Class to get annotation information from target class (it could be as our main launch class or as imported config class during scanning procedure)
1. Class for calling desired scanner
	- class should decide what scanner should be used (including merge of results?), default scanner is ClassPathAnnotationBased scanner
2. ClassPathAnnotationBased scanner.
	- should scan provided package to search all desired classes by specified filter
	- scanner should be implemented using reflection library incapsulated to our ReflectionUtils class
	- 'search package name' is method attribute, 'results filter' is method attribute
3. Filter interface to test if provided class pass the test (predicate).
	- should include predicate information of what classes we are looking for (e.g. - class with @BringComponent annotation or class with annotation derived from @BringComponent annotation)
	- test input class and returns 'true' if class candiate pass the test
	4.1 AnnotationBasedFilter - test if specified annotation present on class
	4.2 SuperAnnotationBasedFilter - test if specified annotation present as parent in target annotation chain
4. Reflection utils 
	- interface to store all functionality for reflection boilerplate code:
		+ search all classes in package
		+ check if annotation present
		+ check if super annotation present (?)
