### ISSUE TITLE
Implement prototype object creation flow

### ISSUE THREAD

**Issue by mykolaFilimonov** [bobocode-breskul/bring#31]
The goal of this ticket is to establish a robust and efficient prototype object creation flow within our system. Unlike a singleton pattern where a single instance is created and shared, the prototype pattern allows for the creation of multiple instances with the same properties as an existing object, serving as a blueprint.

**Comment by s-barabash** [comment]
Bean Creation: When the application requests a bean with the prototype scope from the Bring container, a new instance of the bean is created and returned.

No Container Management: Unlike beans with a singleton scope, Bring does not manage the complete lifecycle of prototype beans. It creates the bean and hands it over to the caller, but it does not keep track of the bean or destroy it.

Client Responsible for Cleanup: Bring does not manage the lifecycle of prototype beans, it is the responsibility of the client (the code that requested the bean) to handle any necessary cleanup or disposal of resources when the bean is no longer needed.
